# Generated by Django 2.1.7 on 2019-03-02 11:56

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontext',
            name='session',
            field=models.CharField(default=bot.models.get_default_value_for_session, max_length=50, unique=True),
        ),
    ]
