# Generated by Django 2.1.7 on 2019-03-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20190302_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropForcasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cropforcasting',
            unique_together={('location', 'season')},
        ),
    ]
